---
version: '3.8'
networks:
  eagerminds_hotel:
    external: true

services:
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - eagerminds_hotel

  mongo-express:
    image: mongo-express:1.0.0-alpha
    restart: always
    ports:
      - "8084:8081"
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    networks:
      - eagerminds_hotel